service: back
provider:
  # boilerplate
  name: aws
  runtime: nodejs12.x
  # you need to make an account on aws and save the creds of a new IAM user on your machine.
  profile: personal

functions:
# this is the name of the main function for your back end. You can make as many as you need - i.e. 
  hello:
  # define the functions entrypoint
    handler: handler.hello
    events:
      - http: GET hello

